include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
  language:
    strict-casts: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

# 配置路径别名
flutter:
  uses-material-design: true

# 配置路径别名
module:
  androidX: true
  android: true
  ios: true
  module:
    androidPackage: com.zijin.tj_tms_mobile
    moduleName: tj_tms_mobile
    androidX: true
    android: true
    ios: true

# 配置路径别名
paths:
  - lib/core
  - lib/data
  - lib/presentation
  - lib/utils
  - lib/widgets
  - lib/presentation/pages
  - lib/data/models

linter:
  rules:
