targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      freezed:
        generate_for:
          include:
            - lib/**.dart
            - test/**.dart
          exclude:
            - lib/**.g.dart
            - lib/**.freezed.dart
            - test/**.g.dart
            - test/**.freezed.dart

# 配置路径别名
module:
  androidX: true
  android: true
  ios: true
  module:
    androidPackage: com.example.tj_tms_mobile
    moduleName: tj_tms_mobile
    androidX: true
    android: true
    ios: true 